# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VirtualPaint(object):
    def setupUi(self, VirtualPaint):
        VirtualPaint.setObjectName("VirtualPaint")
        VirtualPaint.resize(485, 429)
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(11)
        VirtualPaint.setFont(font)
        VirtualPaint.setStyleSheet("background-color: rgb(97, 202, 194);")
        self.label = QtWidgets.QLabel(VirtualPaint)
        self.label.setGeometry(QtCore.QRect(110, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(72)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(VirtualPaint)
        self.pushButton.setGeometry(QtCore.QRect(40, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(VirtualPaint)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 250, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(VirtualPaint)
        self.label_2.setGeometry(QtCore.QRect(350, 90, 391, 331))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/img1.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(VirtualPaint)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vladimir Script")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(VirtualPaint)
        self.label_4.setGeometry(QtCore.QRect(190, 90, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(VirtualPaint)
        self.label_6.setGeometry(QtCore.QRect(260, 180, 121, 101))
        self.label_6.setStyleSheet("border-image: url(:/newPrefix/imagenes/lapiz.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(VirtualPaint)
        self.label_5.setGeometry(QtCore.QRect(-10, 270, 411, 161))
        self.label_5.setStyleSheet("border-image: url(:/newPrefix/imagenes/cuento.png);")
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()

        self.retranslateUi(VirtualPaint)
        QtCore.QMetaObject.connectSlotsByName(VirtualPaint)

    def retranslateUi(self, VirtualPaint):
        _translate = QtCore.QCoreApplication.translate
        VirtualPaint.setWindowTitle(_translate("VirtualPaint", "VirtualPaint"))
        self.label.setText(_translate("VirtualPaint", "Bienvenido"))
        self.pushButton.setText(_translate("VirtualPaint", "Pizarra Virtual"))
        self.pushButton_2.setText(_translate("VirtualPaint", "Cuenta Cuentos"))
        self.label_3.setText(_translate("VirtualPaint", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#3a7974;\">Virtual Paint</span></p></body></html>"))
        self.label_4.setText(_translate("VirtualPaint", "a la plataforma"))
        self.label_5.setText(_translate("VirtualPaint", "\n"
""))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VirtualPaint = QtWidgets.QDialog()
    ui = Ui_VirtualPaint()
    ui.setupUi(VirtualPaint)
    VirtualPaint.show()
    sys.exit(app.exec_())
